[build]
  command = "npm run build:netlify"
  publish = "build"

[build.environment]
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  EXTEND_ESLINT = "false"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://telegram.org https://*.telegram.org https://www.googletagmanager.com https://*.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*.imgur.com https://*.postimg.cc https://i.postimg.cc https://*.unsplash.com https://telegram.org https://*.telegram.org; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.google-analytics.com https://telegram.org https://*.telegram.org;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 